version: "3.9"

services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: split-entrypoints-http
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
    command: http

  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: split-entrypoints-grpc
    ports:
      - "50001:50001"
    env_file:
      - .env
    restart: always
    command: grpc

  consumers:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: split-entrypoints-consumers
    restart: always
    command: consumers

  mongo.db:
    container_name: mongo_split
    image: mongo:3.4
    command: mongod --maxConns 10000
    volumes:
      - mongo:/data/db
      - ./config/storages/mongo/migrations/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

volumes:
  mongo: